on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: action/checkout@v2

      - name: Set Up Cloud SDK
        uses: google-github-actions/setup-gckoud@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}

      - name: Build Docker image
        run: |
          docker build -f Dockerfile-api -t gcr.io/calm-pagoda-458101-h4/kpakam:$GITHUB_SHA .

      - name: Push Docker image to GCR
        run: |
          docker push gcr.io/calm-pagoda-458101-h4/kpakam:$GITHUB_SHA

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - id: "deploy"
        run: |-
          gcloud run deploy kpakam \
          --image=gcr.io/calm-pagoda-458101-h4/your-image-name:${{ github.sha }} \
          --platform=managed \
          --region=europe-west4 \
          --allow-unauthenticated
