on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: action/checkout@v2

      - name: Set Up Cloud SDK
        uses: google-github-actions/setup-gckoud@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}

      - name: Build docker image
        run: |
          docker build -f Dockerfile-api -t gcr.io/skilful-vertex-159007
